config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  resources :contacts
  get "/about" => "pages#about"
  root "pages#home"
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates_presence_of :name, :email
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            ContactMailer.contact_email(name, email, body).deliver
            
            flash[:success] = "Your opinion was sent successfully"
            redirect_to root_path
        else
            flash[:danger] = "Please make sure you fill out all the details"
            render :new
        end
    end
    
    
    private
    
    def contact_params
        params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @basic = Plan.find(1)
    @premium = Plan.find(2)
  end
  
  def about
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    
    
    def new
        @user = User.find(params[:user_id])
        @profile = Profile.new
    end
    
    def create
        @user = User.find(params[:user_id])
        @profile = @user.build_profile(profile_params)
        if @profile.save
            flash[:success] = "Profile updated successfully"
            redirect_to user_path(params[:user_id])
        else
            render :new
        end
    end
    
    
    def edit 
        @user = User.find(params[:user_id])
        @profile = @user.profile
    end
    
    def update
        @user = User.find(params[:user_id])
        @profile = @user.profile
        
        if @profile.update(profile_params)
            flash[:success] = "Profile updated successfully"
            redirect_to user_path(params[:user_id])
        else
            render :edit
        end
    end
    
    private
    
    def profile_params
        params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :contact_email, :phone_number, :description)
    end
    
    def only_current_user
        @user = User.find(params[:user_id])
        redirect_to root_path unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :select_plan, only: [:new] 
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                if resource.plan_id == 2
                    resource.save_with_payment
                else
                    resource.save
                end
            end
        end
    end
    
    private
    
    def select_plan
        unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
            flash[:danger] = "You need to select a plan before proceeding"
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def job_icon
        if @user.profile.job_title == "Developer"
            "<i class='fa fa-code'></i>".html_safe
        
        elsif @user.profile.job_title == "Entrepreneur"
            "<i class='fa fa-lightbulb-o'></i>".html_safe
            
        elsif @user.profile.job_title == "Investor"
            "<i class='fa fa-dollar'></i>".html_safe
        
        end
        
            
    end
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <h2 class="text-center">Contact Us</h2>
            <p class="text-center"><strong>Reach out to us if you have any questions</strong></p>
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.text_field :name, placeholder: "Please enter your name", class:"form-control" %>
                </div>
                <div class="form-group">
                    <%= f.email_field :email, placeholder: "Enter email address", class:"form-control" %>
                </div>
                <div class="form-group">
                    <%= f.text_area :comments, placeholder: "write a query", class:"form-control" %>
                </div>
                    <%= f.submit "Submit", class:"btn btn-primary" %>
            <% end %>
        </div>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasProject</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
  <%= tag :meta, :name => 'stripe-key', :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  
</head>
<body>
  
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class:"navbar-brand" do %>
        <i class="fa fa-users"></i>
        DevMatch
        <% end %>
      </div>
      
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"btn btn-danger navbar-btn" %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class:"btn btn-primary navbar-btn" %>
          <% end %>
          
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact Us", new_contact_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
        </ul>
        
        
      </div>
    </div>
  </nav>

<div class="container">
  <%- flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class:"alert alert-#{name} text-center") %>
  <% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.erb
<h2>About us</h2>
<p>Dev match is the playground for developers entrepreneurs, developers and Investors. Where dots are joined and ideas come to life</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
    <h1>Welcome to devmatch</h1>
    <p>Membership site where enterpreneurs meet developers</p>
</div>
<% if user_signed_in? %>
    <div class="col-md-6">
        <div class="well">
            <h2 class="text-center">Profile</h2>
            <% if current_user.profile %>
                <%= link_to "Show Profile", user_path(current_user), class:"btn btn-block btn-default" %>
                <%= link_to "Edit your profile", edit_user_profile_path(current_user), class:"btn btn-block btn-default" %>
            <% else %>
                <p class="text-center">Create a profile in order to interact with the community. Just click the button below</p>
                <%= link_to "Create a new profile", new_user_profile_path(current_user), class:"btn btn-block btn-default" %>
            <% end %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="well text-center">
            <h2>Community</h2>
            <p>Here you will meet developers, enterpreneurs and investors. They are waiting to hear from you</p>
            <%= link_to "Why dont you meet the community?", users_path, class:"btn btn-block btn-default" %>
        </div>
    </div>
<% else %>
<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h2 class="text-center">Basic plan</h2>
            <h4 class="text-center">Sign up for free</h4>
            <br>
            <%= link_to "Sign up Basic", new_user_registration_path(plan: @basic.id), class:"btn btn-default btn-large btn-block" %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="well">
            <h2 class="text-center">Premium plan</h2>
            <h4 class="text-center">Subscribe for only 10$/ Month and get access to the community and contact information!</h4>
            <%= link_to "Sign up Pro", new_user_registration_path(plan: @premium.id), class:"btn btn-success btn-large btn-block" %>
        </div>
    </div>
</div>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: {multipart: true} do |f| %>
            <div class="form-group">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, placeholder: "please enter your first name", class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, placeholder: "please enter your last name", class:"form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :avatar %>
                <%= f.file_field :avatar, class:"form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :job_title %>
                <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {prompt: "What are you?"}, class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :phone_number %>
                <%= f.text_field :phone_number, placeholder: "Which number can people reach you using?", class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :contact_email %>
                <%= f.text_field :contact_email, placeholder: "please enter your email", class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, placeholder: "say something about yourself", class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.submit "Submit Profile", class:"btn btn-primary" %>
            </div>
            
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit your profile</h1>
        <p class="text-center">Join the comunity and meet thousands of developers, investors and enterpreneurs</p>
        <div class="well">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Fill out your profile</h1>
        <p class="text-center">Join the comunity and meet thousands of developers, investors and enterpreneurs</p>
        <div class="well">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Meet the community</h2>
        <p>You too can appear as part of the community after filling in your profile</p>
        <% @users.each do |user| %>
            <% if user.profile %>
            <div class="row well <%= cycle('blue-bg', '') %>">
                <div class="col-sm-4 text center">
                    <%= link_to user do %>
                        <%= image_tag user.profile.avatar.url(:thumb), class:"avatar" %>
                    <% end %>
                </div>
                <%= link_to user do %>
                    <h3><%= user.profile.first_name %> <%= user.profile.last_name %></h3>
                <% end %>
                <p>
                    <strong><%= user.profile.job_title %></strong>
                    <% if user.plan_id == 2 %>
                    <span class="label label-warning">Pro</span>
                    <% end %>
                </p>
            </div>
                
            <% end %>
        <% end %>
    </div>
</div>


    

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3 text-center">
        <%= image_tag @user.profile.avatar.url(:medium), class: "avatar" %>  
    </div>
    <div class="col-md-6">
        <h2><%= @user.profile.first_name %> <%= @user.profile.last_name %></h2>
        <h3><span class="job-title"><%= job_icon %></span><%= @user.profile.job_title %></h3><br>
        <div class="well description">
            <h3>Description</h3>
            <p><%= @user.profile.description %></p>
        </div>
        <% if user_signed_in? && current_user.plan_id == 2 %>
            <div class=" well contact-info">
                <h3>Contact Information</h3>
                <%= @user.profile.phone_number %><br>
                <%= @user.profile.contact_email %>
            </div>
        <% end %>
</div>